[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
pythonpath = . apps
addopts = 
    --ds=config.settings.test
    --strict-markers
    --no-migrations
    --reuse-db
    --cov=apps/usuarios
    --cov=apps/tarefas
    --cov-report=term-missing

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
