# Generated by Django 5.1.15 on 2026-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status_tarefa',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('vencida', 'Vencida')], default='pendente', max_length=20, verbose_name='Status da tarefa'),
        ),
    ]
